apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-worker
  namespace: flash-sale
  labels:
    app: inventory-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-worker
  template:
    metadata:
      labels:
        app: inventory-worker
    spec:
      containers:
        - name: inventory-worker
          image: flash-sale-inventory-worker:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: flash-sale-config
            - secretRef:
                name: flash-sale-secrets
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
