apiVersion: v1
kind: Secret
metadata:
  name: flash-sale-secrets
  namespace: flash-sale
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://admin:password@postgres-postgresql.flash-sale.svc.cluster.local:5432/flash_sale"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.flash-sale.svc.cluster.local:9092"
